version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        HOST_NAME: ${HOST_NAME}
        HOST_IP: ${HOST_IP}
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
    restart: unless-stopped

  pihole:
    container_name: pihole
    build:
      context: ./pihole
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Australia/Brisbane
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: ${HOST_IP}
    volumes:
      - pihole-config:/etc/pihole
      - pihole-cache:/etc/dnsmasq.d
    restart: unless-stopped

  portainer:
    container_name: portainer
    build:
      context: ./portainer
      args:
        PASSWORD: ${PORTAINER_PASSWORD}
    ports:
      - 9002:9000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-cache:/data
    restart: unless-stopped

  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot:audio
    environment:
      TZ: Australia/Brisbane
      PREFIX: '>'
      NICENESS: '-5'
      TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - redbot-cache:/data
    restart: unless-stopped
    cap_add:
      - SYS_NICE

volumes:
  pihole-config: {}
  pihole-cache: {}
  portainer-cache: {}
  redbot-cache: {}
