version: "3.7"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  registry:
    container_name: registry
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ${REGISTRY_DIR}:/var/lib/registry

  steam-server:
    container_name: steam-server
    build: ./steamcmd
    ports:
      - 7778:7778/udp
      - 27016:27016/udp
      - 8080:8080/tcp
      - 20561:20561/udp
      - 123:123/udp
    environment:
      - STEAM_APP_ID
      - STEAM_SERVER_DIR
    volumes:
      - ${STEAM_SERVER_DIR}/:/home/steam/steamcmd/kf2server
