version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      args:
        HOST_NAME: ${HOST_NAME}
        PUBLIC_HOST_NAME: ${PUBLIC_HOST_NAME}
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
    restart: unless-stopped

  pihole:
    build:
      context: ./pihole
      args:
        HOST_NAME: ${HOST_NAME}
        HOST_IP: ${HOST_IP}
        PIHOLE_ALIASES: ${PIHOLE_ALIASES}
    ports:
      - 4200:80
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Australia/Brisbane
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: ${HOST_IP}
    volumes:
      - pihole-config:/etc/pihole
      - pihole-cache:/etc/dnsmasq.d
    restart: unless-stopped

  hello:
    build:
      context: ./hello
    restart: unless-stopped

  portainer:
    build:
      context: ./portainer
      args:
        PASSWORD: ${PORTAINER_PASSWORD}
    ports:
      - 4201:9000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-cache:/data
    restart: unless-stopped

  redbot:
    image: phasecorex/red-discordbot:audio
    environment:
      TZ: Australia/Brisbane
      PREFIX: '>'
      NICENESS: '-5'
      TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - redbot-cache:/data
    restart: unless-stopped
    cap_add:
      - SYS_NICE

  ddns:
    build:
      context: ./ddns
      args:
        DDNS_CRON: ${DDNS_CRON}
        DDNS_USER: ${DDNS_USER}
        DDNS_PASS: ${DDNS_PASS}
        DDNS_ENDPOINT: ${DDNS_ENDPOINT}
        PUBLIC_HOST_NAME: ${PUBLIC_HOST_NAME}
    restart: unless-stopped

volumes:
  pihole-config: {}
  pihole-cache: {}
  portainer-cache: {}
  redbot-cache: {}
