version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
      args:
        HOST_NAME: ${HOST_NAME}
        PUBLIC_HOST_NAME: ${PUBLIC_HOST_NAME}
    ports:
      - 80:80
    restart: unless-stopped

  pihole:
    build:
      context: ./pihole
      args:
        HOST_NAME: ${HOST_NAME}
        HOST_IP: ${HOST_IP}
        PIHOLE_ALIASES: ${PIHOLE_ALIASES}
    ports:
      - 4200:80
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Australia/Brisbane
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: ${HOST_IP}
    volumes:
      - pihole-config:/etc/pihole
      - pihole-cache:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  hello:
    build:
      context: ./hello
    ports:
      - 4201:80
    restart: unless-stopped

  portainer:
    build:
      context: ./portainer
      args:
        PASSWORD: ${PORTAINER_PASSWORD}
    ports:
      - 4202:9000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-cache:/data
    restart: unless-stopped

  ytdl:
    image: tzahi12345/youtubedl-material:nightly
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
    volumes:
      - ./ytdl/data/appdata:/app/appdata
      - ./ytdl/data/users:/app/users
      - ./ytdl/data/out/audio:/app/audio
      - ./ytdl/data/out/video:/app/video
      - ./ytdl/data/out/subscriptions:/app/subscriptions
    ports:
      - 8998:17442
    restart: unless-stopped

volumes:
  pihole-config: {}
  pihole-cache: {}
  portainer-cache: {}
